### PR TITLE
Allow composition

### PR DESCRIPTION
**Pull request by b1rdex**
My original idea was to provide ability to composite sphinx configuration from classes instead of declaring it line by line.
You can view example in `CompositionTest`.

Sorry, I introduced many public api changes. Some of them was must — e.g. `add*` should accept instance, not create one. Some of them was not — e.g. renames of `iterate*`.

Also, I separated some (de)serialization logic, because concerns solving logic should be separated.

I hope you understood my original idea besides introducing major api changes.
Please tell me what do you think about such a big rewrite.
Also I leaved some `todo` comments with my thoughts, please comment them too.

### CODE REVIEW

**Comment by b1rdex** [comment]
Another thing such composition allows:
```php
abstract class BaseIndex extends Index
{
    public function __construct(Configuration $configuration)
    {
        parent::__construct($configuration, $this->getIndexName());

        $this->addOption(eIndexOption::MORPHOLOGY(), 'lemmatize_ru_all, lemmatize_en_all');
        // any other common index configuration
    }

    /**
     * This method must return index name
     *
     * @return string
     */
    abstract protected function getIndexName(): string;
}

class RealIndex1 extends BaseIndex
{}
class RealIndex2 extends BaseIndex
{}
```

**Comment by voksiv** [comment]
We can not accept this pull because backward compatibility is lost because of changes in the public api and we are using this library in production. 

Also in our code rules we don't use strict types.

**Comment by b1rdex** [comment]
Sad to hear. Have you considered releasing new major version?

**Comment by voksiv** [comment]
No, we have no plans to develop this library at the moment. Now it covers all the business requirements that we need. However, it is distributed by the MIT license, so you can fork it and use it as you want.

**Pull request closed without merging**
